app-yamls:
    comesa-testsEnabled: true
    comesa-testsSyncWave: 0

comesa-tests:
    namespace: comesa-tests
    ttkHelmVersion: 17.4.0
    ttkHelmValues: {}
    comesaTestsDockerImageTag: latest
    syncWave: 4
    testConfig:
        dfspConfig:
            test-zmw-dfsp:
                name: test-zmw-dfsp
                enabled: true
                currency: ZMW
                endpoint: payer
                happyPathMSISDN: 16665551001
            test-mwk-dfsp:
                name: test-mwk-dfsp
                enabled: true
                currency: MWK
                endpoint: payee
                happyPathMSISDN: 16665551002
            test-ugx-dfsp:
                name: test-ugx-dfsp
                enabled: true
                currency: UGX
                endpoint: payee
                happyPathMSISDN: 16665551003
        multiSchemeConfig:
            test-zmw-dfsp:
                dfsp: test-zmw-dfsp
                sendAmount: 10
                targets:
                    test-mwk-dfsp:
                        dfsp: test-mwk-dfsp
                    test-ugx-dfsp:
                        dfsp: test-ugx-dfsp
            test-mwk-dfsp:
                dfsp: test-mwk-dfsp
                sendAmount: 10
                targets:
                    test-zmw-dfsp:
                        dfsp: test-zmw-dfsp
                    test-ugx-dfsp:
                        dfsp: test-ugx-dfsp
            test-ugx-dfsp:
                dfsp: test-ugx-dfsp
                sendAmount: 15
                targets:
                    test-zmw-dfsp:
                        dfsp: test-zmw-dfsp
                    test-mwk-dfsp:
                        dfsp: test-mwk-dfsp
