apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - comesa-tests-config.yaml
  - vs.yaml
  - pvc.yaml
  # - comesa-tests-job.yaml
  - comesa-test-runner.yaml
helmCharts:
  - name: ml-testing-toolkit
    releaseName: ttk
    version: ${app.ttkHelmVersion}
    repo: http://mojaloop.io/helm/repo
    valuesFile: values-ttk-default.yaml
    namespace: comesa-tests
    additionalValuesFiles:
      - values-ttk-override.yaml
