apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - comesa-tests-config.yaml
  - vs.yaml
  - comesa-tests-job.yaml
helmCharts:
  - name: ml-testing-toolkit
    releaseName: ttk
    version: ${app.ttkHelmVersion}
    repo: http://mojaloop.io/helm/repo
    valuesFile: values-ttk-default.yaml
    namespace: comesa-tests
    additionalValuesFiles:
      - values-ttk-override.yaml
  - name: nginx
    releaseName: test
    version: 19.0.1
    repo: oci://registry-1.docker.io/bitnamicharts
    valuesFile: values-nginx.yaml
    namespace: comesa-tests

