apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - comesa-test-job.yaml
configMapGenerator:
  - name: comesa-test-collections
    namespace: mojaloop
    files:
      - collections/scheme_rule_tests/mwk_as_payer_tests.json
      - collections/scheme_rule_tests/zmw_as_payer_tests.json
  - name: comesa-test-environments
    namespace: mojaloop
    files:
      - environments/pm4ml-default-environment.json
