apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comesa-test-reports-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ${app.storageClass}