apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comesa-test-reports-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ${app.storageClass}