# %{ if app.comesa-testsEnabled }
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "${app.comesa-testsSyncWave}"
  name: comesa-tests
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    path: apps/comesa-tests
    repoURL: ${cluster.gitlabProjectUrl}
    targetRevision: HEAD
  destination:
    namespace: ${app.comesa-testsNamespace}
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
      - PruneLast=true
# %{ endif }
