# %{ if app.comesa-testsEnabled }
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "${app.comesa-testsSyncWave}"
  name: comesa-tests
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    path: apps/comesa-tests
    repoURL: ${cluster.gitlabProjectUrl}
    targetRevision: HEAD
  destination:
    namespace: test-zmw-dfsp
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
      - PruneLast=true
# %{ endif }
