name: Summarize Tests and Update Release Notes
on:
  push:
    tags: [ 'v*.*.*' ]
jobs:
  summarize-tests:
    name: Summarize Tests and Update Release Notes
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Process JSON Files
      id: process_files
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          const testFolder = 'ttk-test-collection/multi-scheme-tests';
          const summaries = [];
          
          console.log(`Looking for JSON files in: ${testFolder}`);
          console.log(`Directory exists: ${fs.existsSync(testFolder)}`);
          
          if (!fs.existsSync(testFolder)) {
            core.setFailed(`Directory not found: ${testFolder}`);
            return;
          }
          
          // Get all JSON files and sort them
          const allFiles = fs.readdirSync(testFolder)
            .filter(f => f.endsWith('.json'))
            .sort();
          
          console.log(`Found ${allFiles.length} JSON files: ${allFiles.join(', ')}`);
          
          // Process each file
          for (const filename of allFiles) {
            const filePath = path.join(testFolder, filename);
            console.log(`\n--- Processing: ${filename} ---`);
            
            try {
              const fileContent = fs.readFileSync(filePath, 'utf8');
              const data = JSON.parse(fileContent);
              
              const testCases = data.test_cases || [];
              console.log(`Found ${testCases.length} test cases in ${filename}`);
              
              testCases.forEach((tc, idx) => {
                const name = tc.name || 'No Name';
                const metaInfo = tc.meta?.info || 'No Meta Info';
                summaries.push(`File: ${filename}\nTest Case: ${name}\nMeta Info: ${metaInfo}\n`);
                console.log(`  - Test case ${idx + 1}: ${name}`);
              });
              
            } catch (error) {
              console.error(`ERROR: Failed to process ${filename}: ${error.message}`);
              continue;
            }
          }
          
          console.log(`\n=== Total test cases processed: ${summaries.length} ===`);
          
          // Save summary to file and output
          const summaryOutput = summaries.join('\n');
          fs.writeFileSync('summary.txt', summaryOutput, 'utf8');
          
          // Set output using core.setOutput (handles multi-line automatically)
          core.setOutput('summary', summaryOutput);
          
          return summaryOutput;
    
    - name: Debug - Show Summary File
      run: cat summary.txt
    
    - name: Run AI inference
      id: inference
      uses: actions/ai-inference@v1
      with:
        max-tokens: 1500
        prompt: |
          Summarize these test cases in bullet points:
          ${{ steps.process_files.outputs.summary }}
    
    - name: Clone Wiki Repository
      run: |
        git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki
        cd wiki
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Update Wiki with Test Summary
      run: |
        cd wiki

        # Create/Update Release-Test-Summaries.md page
        WIKI_PAGE="Home.md"

        cat > "$WIKI_PAGE" << 'EOF'
        # Test Cases Summary
        
        ${{ steps.inference.outputs.response }}
        
        EOF
      
        # Commit and push changes
        git add "$WIKI_PAGE"
        
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Updater test summary"
          git push origin master
          echo "Wiki updated successfully"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
